graph TD
    subgraph SimpleNet
    bc(BaseCube) --> ImageCube 
    ImageCube --> FourierLayer
    FourierLayer --> DataConnector 
    end
    ad[[Dataset]] --> DataConnector 
    DataConnector --> il([Loss])