name: build and deploy docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install doc deps
        run: |
          pip install .'[dev]'
      - name: Install Pandoc dependency
        run: |
          sudo apt-get install pandoc
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Install mermaid.js dependency
        run: |
          npm install @mermaid-js/mermaid-cli
      - name: Build the docs
        run: |
          make -C docs clean
          make -C docs html MERMAID_PATH="../node_modules/.bin/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
