name: gh-pages docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install doc deps
        run: |
          pip install .'[docs]'
      - name: Install Pandoc dependency
        run: |
          sudo apt-get install pandoc
      - name: Set up node
        uses: actions/setup-node@v2
      - name: Install mermaid.js dependency
        run: |
          npm install @mermaid-js/mermaid-cli
      - name: Cache/Restore the .mpol folder cache
        uses: actions/cache@v2
        env:
          cache-name: cache-mpol-dls
        with:
          # files are stored in .mpol
          path: ~/.mpol
          # the "key" is the hash of the download script
          key: ${{ hashFiles('docs/download_external_files.py') }}
      - name: Download large files
        run: |
          python3 docs/download_external_files.py
      - name: Build the docs
        run: |
          make -C docs clean
          make -C docs html MERMAID_PATH="../node_modules/.bin/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
